trigger:
  branches:
    include:
      - Desarrollo

variables:
  - group: GitHubSecrets
  - group: AZURE_TOKEN

pool:
  name: 'Default'

steps:
# Paso 1: Verificar el agente
- script: echo 'Iniciando Desarrollo para Front-End...'
  displayName: 'Verificar Agente'

# Paso 2: Verificar si package.json existe
- script: |
    echo Verificando si package.json existe...
    cd ProyNaVishe_FRONT
    dir
  displayName: 'Verificar existencia de package.json'

# Paso 3: Instalar dependencias de React
- script: |
    cd proynavishe_front
    npm install
  displayName: 'Instalar dependencias de React'

# Paso 4: Validaci贸n de c贸digo y ejecuci贸n de pruebas
- script: |
    cd proynavishe_front
    npm run lint
    npm test
  displayName: 'Validaci贸n de c贸digo y pruebas'

- task: PublishTestResults@2
  inputs:
    testResultsFiles: '**/TEST-*.xml'
    testRunTitle: 'Resultados de Pruebas Frontend'
  displayName: 'Publicar los resultados de las pruebas'

# Paso 5: Empaquetar la aplicaci贸n en un archivo .zip
- script: |
    echo "Empaquetando la aplicaci贸n..."
    powershell Compress-Archive -Path $(Build.SourcesDirectory)\* -DestinationPath $(Build.ArtifactStagingDirectory)\NaVisheWebApp.zip
  displayName: 'Empaquetar la aplicaci贸n'

# Paso 6: Despliegue a QA
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'AzureForStudentsConnection'
    appName: 'NaVisheWebApp'
    package: '$(Build.ArtifactStagingDirectory)/NaVisheWebApp.zip'
    displayName: 'Desplegar a QA'

# Paso 7: Notificaci贸n de despliegue
- script: echo " Despliegue completado en el entorno de QA para Front-End"
  displayName: 'Finalizaci贸n del Deploy'
