trigger:
  branches:
    include:
      - Desarrollo

variables:
  - group: GitHubSecrets
  - group: AZURE_TOKEN

pool:
  name: 'Default'

steps:
# Paso 1: Verificar el agente
- script: echo 'Iniciando Desarrollo para Front-End...'
  displayName: 'Verificar Agente'

# Paso 2: Instalar dependencias de React en la carpeta principal
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Instalar Node.js'

- script: |
    npm install
  displayName: 'Instalar dependencias principales'

# Paso 3: Verificar existencia de package.json en el directorio frontend
- script: |
    echo Verificando si package.json existe en el directorio principal...
    dir frontend
  displayName: 'Verificar existencia de package.json'

# Paso 4: Iterar sobre las subcarpetas y realizar instalación de dependencias y pruebas
- script: |
    cd NaVishe/mf-gestionarTrabajador
    npm install
    npm run lint
    npm test
  displayName: 'Instalar dependencias y correr pruebas en mf-gestionarTrabajador'

- script: |
    cd NaVishe/mf-camaras
    npm install
    npm run lint
    npm test
  displayName: 'Instalar dependencias y correr pruebas en mf-camaras'

# Repite el proceso para las demás carpetas como NaVishe/mf-dashboard, etc.

# Paso 5: Publicar resultados de las pruebas
- task: PublishTestResults@2
  inputs:
    testResultsFiles: '**/TEST-*.xml'
    testRunTitle: 'Resultados de las pruebas Front-End'
  displayName: 'Publicar los resultados de las pruebas'
