trigger:
  branches:
    include:
      - Desarrollo

variables:
  - group: GitHubSecrets
  - group: AZURE_TOKEN

pool:
  name: 'Default'

steps:
# Paso 1: Verificar el agente
- script: echo 'Iniciando Desarrollo para Front-End...'
  displayName: 'Verificar Agente'

# Paso 2: Instalar dependencias de React
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Instalar Node.js'

- script: |
    echo "Verificando la ubicación de package.json..."
    cd $(Build.SourcesDirectory)/frontend  # Cambié esta parte para asegurar que estés en la carpeta correcta
    dir  # Esto listará los archivos y carpetas en la ubicación actual
    npm install
  displayName: 'Instalar dependencias de React'

# Paso 3: Validación de código y ejecución de pruebas
- script: |
    npm run lint
    npm test
  displayName: 'Validación de código y pruebas'

- task: PublishTestResults@2
  inputs:
    testResultsFiles: '**/TEST-*.xml'
    testRunTitle: 'Resultados de Pruebas Backend'
  displayName: 'Publicar los resultados de las pruebas'

# Paso 4: Empaquetar la aplicación en un archivo .zip
- script: |
    echo "Empaquetando la aplicación..."
    powershell Compress-Archive -Path $(Build.SourcesDirectory)/frontend/* -DestinationPath $(Build.ArtifactStagingDirectory)/NaVisheWebApp.zip
  displayName: 'Empaquetar la aplicación'

# Paso 5: Despliegue a QA
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'AzureForStudentsConnection'
    appName: 'NaVisheWebApp'
    package: '$(Build.ArtifactStagingDirectory)/NaVisheWebApp.zip'
    displayName: 'Desplegar a QA'

# Paso 6: Notificación de despliegue
- script: echo "🚀 Despliegue completado en el entorno de QA para Front-End"
  displayName: 'Finalización del Deploy'
