trigger:
  branches:
    include:
      - Desarrollo

variables:
  - group: GitHubSecrets
  - group: AZURE_TOKEN

pool:
  name: 'Default'

steps:
# Paso 1: Verificar el agente
- script: echo 'Iniciando Desarrollo para Front-End...'
  displayName: 'Verificar Agente'

# Paso 2: Verificar existencia de package.json
- script: |
    echo Verificando si package.json existe...
    dir NaVishe
  displayName: 'Verificar existencia de package.json'

# Paso 3: Instalar dependencias de React
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Instalar Node.js'

# Paso 4: Navegar al directorio correcto y ejecutar npm install
- script: |
    cd NaVishe
    npm install
  displayName: 'Instalar dependencias de React'

# Paso 5: Validación de código y ejecución de pruebas
- script: |
    npm run lint
    npm test
  displayName: 'Validación de código y pruebas'

# Paso 6: Publicar resultados de las pruebas
- task: PublishTestResults@2
  inputs:
    testResultsFiles: '**/TEST-*.xml'
    testRunTitle: 'Resultados de Pruebas Front-End'
  displayName: 'Publicar los resultados de las pruebas'

# Paso 7: Empaquetar la aplicación en un archivo .zip
- script: |
    echo "Empaquetando la aplicación..."
    powershell Compress-Archive -Path $(Build.SourcesDirectory)\* -DestinationPath $(Build.ArtifactStagingDirectory)\NaVisheWebApp.zip
  displayName: 'Empaquetar la aplicación'

# Paso 8: Despliegue a QA
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'AzureForStudentsConnection'
    appName: 'NaVisheWebApp'
    package: '$(Build.ArtifactStagingDirectory)/NaVisheWebApp.zip'
    displayName: 'Desplegar a QA'

# Paso 9: Notificación de despliegue
- script: echo "🚀 Despliegue completado en el entorno de QA para Front-End"
  displayName: 'Finalización del Deploy'
