trigger:
  branches:
    include:
      - Desarrollo

variables:
  - group: GitHubSecrets
  - group: AZURE_TOKEN

pool:
  name: 'Default'

steps:
- script: echo 'Iniciando Desarrollo para Front-End...'
  displayName: 'Verificar Agente'

- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Instalar Node.js'

- script: |
    cd proynavishe_front
    npm install
  displayName: 'Instalar dependencias de React'

- script: |
    npm run lint
    npm test
  displayName: 'Validaci贸n de c贸digo y pruebas'

- task: PublishTestResults@2
  inputs:
    testResultsFiles: '**/TEST-*.xml'
    testRunTitle: 'Resultados de Pruebas Backend'
  displayName: 'Publicar los resultados de las pruebas'

- script: |
    echo "Empaquetando la aplicaci贸n..."
    powershell Compress-Archive -Path $(Build.SourcesDirectory)\* -DestinationPath $(Build.ArtifactStagingDirectory)\NaVisheWebApp.zip
  displayName: 'Empaquetar la aplicaci贸n'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'AzureForStudentsConnection'
    appName: 'NaVisheWebApp'
    package: '$(Build.ArtifactStagingDirectory)/NaVisheWebApp.zip'
    displayName: 'Desplegar a QA'

- script: echo " Despliegue completado en el entorno de QA para Front-End"
  displayName: 'Finalizaci贸n del Deploy'
