trigger:
  branches:
    include:
      - main  # Ejecuta el pipeline cuando haya cambios en main

pr:
  branches:
    include:
      - main  # También ejecuta el pipeline en pull requests a main

pool:
  vmImage: 'ubuntu-latest'  # Usa una máquina Linux estándar

steps:
  - checkout: self  # Clona el repositorio

  - script: echo "Pipeline básico de Frontend ejecutándose..."
    displayName: "Mensaje de inicio"

  - script: ls -la
    displayName: "Listar archivos en el repositorio"

  - script: echo "Fin del pipeline"
    displayName: "Finalizar ejecución"
